# SPDX-License-Identifier: MIT

inherit cmake externalsrc

EXTERNALSRC ?= "${OPENAUTOSAR_SOURCE_DIR}"
EXTERNALSRC_BUILD ?= "${WORKDIR}/build"

OECMAKE_GENERATOR ?= "Unix Makefiles"
EXTRA_OECMAKE += "-DOA_BUILD_TESTS=OFF"
EXTRA_OECMAKE += "-DOA_ENABLE_SANITIZERS=OFF"
EXTRA_OECMAKE += "-DOA_ENABLE_LINK_MAPS=ON"
EXTRA_OECMAKE += "-DOA_WARNINGS_AS_ERRORS=ON"
