# SPDX-License-Identifier: MIT

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "openautosar"
BBFILE_PATTERN_openautosar = "^${LAYERDIR}/"
BBFILE_PRIORITY_openautosar = "7"

LAYERSERIES_COMPAT_openautosar = "scarthgap"

OPENAUTOSAR_LAYER_DIR := "${LAYERDIR}"
OPENAUTOSAR_SOURCE_DIR ??= "${OPENAUTOSAR_LAYER_DIR}/.."

OPENAUTOSAR_AGL_RELEASE_NAME = "Ultimate Unagi"
OPENAUTOSAR_AGL_RELEASE_VERSION = "21.0.2"
OPENAUTOSAR_AGL_BRANCH = "unagi"
OPENAUTOSAR_AGL_MANIFEST = "unagi_21.0.2.xml"
OPENAUTOSAR_YOCTO_RELEASE = "scarthgap-5.0.18"
OPENAUTOSAR_MACHINE = "qemux86-64"
