#!/usr/bin/env bash
# SPDX-License-Identifier: MIT

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
governance="${repo_root}/docs/governance/program-governance.yaml"
backlog="${repo_root}/requirements/backlog/initial-backlog.yaml"
source_baseline="${repo_root}/requirements/autosar/source-baseline.yaml"
api_index="${repo_root}/docs/api/PUBLIC_API_INDEX.md"
service_index="${repo_root}/docs/services/PLATFORM_SERVICE_INDEX.md"
runtime_service="${repo_root}/meta-openautosar/recipes-platform"
runtime_service+="/openautosar-runtime/files/openautosar-bootstrap.service"
dashboard_service="${repo_root}/meta-openautosar/recipes-ui"
dashboard_service+="/openautosar-dashboard/files/openautosar-dashboard.service"
evidence="${repo_root}/out/evidence/program-governance/validation.json"
missing=()

json_array() {
  local first="true"
  printf '['
  for item in "$@"; do
    if [[ "${first}" == "true" ]]; then
      first="false"
    else
      printf ', '
    fi
    printf '"%s"' "${item}"
  done
  printf ']'
}

require_file() {
  local path="$1"
  local name="$2"
  if [[ ! -f "${path}" ]]; then
    missing+=("${name}")
  fi
}

require_spdx() {
  local path="$1"
  local name="$2"
  if [[ ! -f "${path}" ]] || ! head -n 5 "${path}" | grep -q "SPDX-License-Identifier: MIT"; then
    missing+=("${name}:spdx")
  fi
}

require_text() {
  local path="$1"
  local pattern="$2"
  local name="$3"
  if [[ ! -f "${path}" ]] || ! grep -Fq "${pattern}" "${path}"; then
    missing+=("${name}")
  fi
}

require_count() {
  local path="$1"
  local pattern="$2"
  local expected="$3"
  local name="$4"
  local count="0"
  if [[ -f "${path}" ]]; then
    count="$(grep -c "${pattern}" "${path}" || true)"
  fi
  if [[ "${count}" != "${expected}" ]]; then
    missing+=("${name}:${count}/${expected}")
  fi
}

require_min_count() {
  local path="$1"
  local pattern="$2"
  local minimum="$3"
  local name="$4"
  local count="0"
  if [[ -f "${path}" ]]; then
    count="$(grep -c "${pattern}" "${path}" || true)"
  fi
  if [[ "${count}" -lt "${minimum}" ]]; then
    missing+=("${name}:${count}<${minimum}")
  fi
}

require_no_matches() {
  local pattern="$1"
  local name="$2"
  shift 2
  if rg -n "${pattern}" "$@" >/dev/null 2>&1; then
    missing+=("${name}")
  fi
}

for path in "${governance}" "${backlog}" "${source_baseline}" "${api_index}" "${service_index}"; do
  require_file "${path}" "${path#${repo_root}/}"
  require_spdx "${path}" "${path#${repo_root}/}"
done

require_text "${governance}" "schema: openautosar.program-governance.v1" \
  "governance-schema"
require_text "${governance}" "engineering_hours_per_week: 10" \
  "governance-capacity-hours"
require_text "${governance}" "active_major_workstream_limit: 1" \
  "governance-active-workstream-limit"
require_count "${governance}" '^  - id: FD-' 18 "confirmed-decisions"
require_count "${governance}" '^  - id: BQ-' 12 "bootstrap-open-questions"
require_count "${governance}" '^  - id: R4Q-' 15 "round4-contract-questions"
require_count "${governance}" '^  - id: ROLE-' 12 "implementation-team-roles"
require_count "${governance}" '^  - id: CR-' 18 "coding-rules"

require_text "${backlog}" "schema: openautosar.initial-backlog.v1" "backlog-schema"
require_count "${backlog}" '^  - id: EPIC-' 13 "backlog-epics"
require_min_count "${backlog}" '^      - id: EPIC-' 90 "backlog-items"

require_text "${source_baseline}" "schema: openautosar.official-source-baseline.v1" \
  "source-baseline-schema"
require_text "${source_baseline}" "autosar_documents_committed: false" \
  "source-baseline-autosar-doc-policy"
require_count "${source_baseline}" '^  - id: SRC-' 14 "source-baseline-sources"

for topic in Purpose Lifecycle Threading Ownership Errors Timing Example "Compatibility status"; do
  require_text "${api_index}" "${topic}:" "public-api-topic-${topic}"
done

for topic in \
  "Context diagram" \
  "Sequence diagram" \
  "State machine" \
  "Trust boundary" \
  "Deployment model" \
  "Failure table" \
  "Verification strategy"; do
  require_text "${service_index}" "${topic}:" "platform-service-topic-${topic}"
done

require_text "${repo_root}/build/cmake/OpenAutosarCompilerOptions.cmake" \
  "cxx_std_20" "coding-rule-cxx20"
require_text "${repo_root}/CMakeLists.txt" "CMAKE_CXX_VISIBILITY_PRESET hidden" \
  "coding-rule-hidden-visibility"
require_text "${runtime_service}" "User=openautosar" "coding-rule-no-root-runtime"
require_text "${runtime_service}" "NoNewPrivileges=true" \
  "coding-rule-no-new-privileges-runtime"
require_text "${dashboard_service}" "User=openautosar" "coding-rule-no-root-dashboard"
require_text "${repo_root}/tools/oa_cli/model.py" "Generated by oa-cli; do not edit manually." \
  "coding-rule-generated-marker"

if find "${repo_root}/bsw" "${repo_root}/platform" "${repo_root}/integration" "${repo_root}/apps" \
  -type f -name '*.h' ! -path '*/include/*' -print | grep -q .; then
  missing+=("coding-rule-public-headers-under-include")
fi

require_no_matches '\.detach\s*\(' "coding-rule-no-detached-threads" \
  "${repo_root}/bsw" "${repo_root}/platform" "${repo_root}/integration" "${repo_root}/apps"
require_no_matches 'while\s*\(\s*true\s*\)|for\s*\(\s*;;\s*\)' \
  "coding-rule-no-unbounded-production-loop" \
  "${repo_root}/bsw" "${repo_root}/platform" "${repo_root}/integration" "${repo_root}/apps"

if find "${repo_root}" \
  -path "${repo_root}/.git" -prune -o \
  -path "${repo_root}/out" -prune -o \
  -type f -name 'AUTOSAR_*.pdf' -print | grep -q .; then
  missing+=("source-baseline-no-committed-autosar-pdfs")
fi

confirmed_decision_count="$(grep -c '^  - id: FD-' "${governance}" || true)"
bootstrap_question_count="$(grep -c '^  - id: BQ-' "${governance}" || true)"
round4_question_count="$(grep -c '^  - id: R4Q-' "${governance}" || true)"
team_role_count="$(grep -c '^  - id: ROLE-' "${governance}" || true)"
coding_rule_count="$(grep -c '^  - id: CR-' "${governance}" || true)"
backlog_epic_count="$(grep -c '^  - id: EPIC-' "${backlog}" || true)"
backlog_item_count="$(grep -c '^      - id: EPIC-' "${backlog}" || true)"
source_count="$(grep -c '^  - id: SRC-' "${source_baseline}" || true)"

mkdir -p "$(dirname "${evidence}")"
status="valid"
if [[ "${#missing[@]}" -gt 0 ]]; then
  status="invalid"
fi

{
  printf '{\n'
  printf '  "schema": "openautosar.program-governance.validation.v1",\n'
  printf '  "status": "%s",\n' "${status}"
  printf '  "governance_register": "docs/governance/program-governance.yaml",\n'
  printf '  "backlog_register": "requirements/backlog/initial-backlog.yaml",\n'
  printf '  "source_baseline": "requirements/autosar/source-baseline.yaml",\n'
  printf '  "confirmed_decision_count": %s,\n' "${confirmed_decision_count}"
  printf '  "bootstrap_open_question_count": %s,\n' "${bootstrap_question_count}"
  printf '  "round4_contract_question_count": %s,\n' "${round4_question_count}"
  printf '  "implementation_team_role_count": %s,\n' "${team_role_count}"
  printf '  "coding_rule_count": %s,\n' "${coding_rule_count}"
  printf '  "backlog_epic_count": %s,\n' "${backlog_epic_count}"
  printf '  "backlog_item_count": %s,\n' "${backlog_item_count}"
  printf '  "source_count": %s,\n' "${source_count}"
  printf '  "missing": '
  json_array "${missing[@]}"
  printf '\n}\n'
} >"${evidence}"

if [[ "${status}" != "valid" ]]; then
  printf 'program governance invalid: %s\n' "${missing[*]}" >&2
  exit 1
fi

echo "program governance valid: ${evidence}"
